theme: jekyll-theme-minimal
title: Gleitschirm Social Media App
description: Das ist die Projekt Website des Gleitschirm Social Media Apps. In dem beschriebenen Repository sind sowohl die Client wie auch die Server Umgebungen vorzufinden.
github_username:  timvonfelten
github_username:  MattiaBaertschi
accent_image: ./images/glider.gif